@startuml


rectangle "Основные потоки" {
    map "ID: 1" as id1 {
        Краткое описание => Формирует заказ на основе корзиины
        Действующие лица => Пользователь, Система
        Предусловие => Клиент запросил оформить заказ
        Постусловие => Заказ оформлен
        Основной поток => -
        Альтернативные потоки => 1.1, 1.2
    }
}

rectangle "Альтернативные потоки" {


    map "ID: 1.2" as id3 {
        Краткое описание => Совершает копирование в БД
        Действующие лица => Система управления базой данных
        Предусловие => Формируется заказ на основе корзины пользователя
        Постусловие => Копирование завершено
        Основной поток => 1
        Альтернативные потоки => -
    }
    map "ID: 1.1" as id2 {
        Краткое описание => Совершает банковскую транзакцию
        Действующие лица => Банковская система
        Предусловие => Установлена оплата картой
        Постусловие => Завершение оплаты успехом или ошибкой
        Основной поток => 1
        Альтернативные потоки => -
    }
}

id1 --> id2
id1 --> id3

@enduml