@startuml

|Пользователь|
start
:Запросить оформление заказа;

|Система|
:Объявить статус оплаты как «оплата не запрошена»;
fork
    if (Оплата картой) then (нет)
        |Система|
    else (да)
        |Банковская система|
        :Списать средства;
        |Система|
        :Перехвтаить статус оплаты;
        note right
            Возможный статус оплаты:
                - Оплачен
                - Отклонён
        end note
    endif
fork again
    |База данных|
    :Объявить заказ;
    :Копирование товаров из корзины в заказ;
    :Очистить корзину пользователя;
    |Система|
    :Перехватить ИД заказа;
end fork

if (статус оплаты = «оплачен») then (да)
    :Установить способ оплаты «По карте»;
    :Добавить детали банковской транзакции в результат;
else (нет)
    :Установить способ оплаты «Наличными»;
    if (статус оплаты = «отклонён») then (да)
        :Добавить подробности ошибки к результату;
    endif
endif

:Установить заказ как «Оформленный»;
:Вернуть результат пользователю;
|Пользователь|
:Перехватить результат;
stop

@enduml