@startuml

package "Boundary" {
    class "ЭкранСборкиПК" as pcBuild {
        + Поиск(:Строка): ЭкранКомплектующих
        + НастроитьСлот(:Слот): ЭкранКомплектующих
        + УстановитьПККакТекущий(:Конфигурация)
        + УстановитьТипТекущегоПК(:ТипПК)
        + ДобавитьТекущийПКВКорзину()
        + ОчиститьТекущийПК()
        + УстановитьПредустановленнуюКонфигурацию(:Конфигурация)
        + ВернутьСписокКонфигураций(): Конфигурация[0..*]
    }

    class "ЭкранКомплектующих" as partBuild {
        + ПрименитьПоиск(:Строка)
        + УчестьСовместимостьСоСлотом(:Слот)
        + ОтоброзитьСписки()
        + ДобавитьКомплектующееВКорзину()
        + ВыбратьКомплектующее()
    }
}

package "Controller" {
    class "ЭкспертКомплектующих" as partManager {
        + ПредопределённыеКонфигурации: Конфигурация[0..*]
        + СделатьАвтоподбор(:Слот): Комплектующее
        + СовершитьПоиск(запрос: Строка[0..1], :Слот[0..1]): Комплектующее[0..*]
    }

    class "КорзинныйЭксперт" as basketManager {
        + ДобавитьПКВКорзину(:Конфигруация)
        + ДобавитьКомплектующееВКорзину(:Комплектующее)
    }
}

package "Entity" {
    class "Корзина" as basket {
        + ДобавитьВКорзину(:Товар)
    }

    class "Товар" as item{

    }

    class "Слот" as slot {
        + ПроверитьСовместимость(:Комплектующее)
        + Установить(:Комплектующее)
        + Очистить()
    }

    class "Комплектующее" as part extends item {
        + ПеречислитьВсе(): Комплектующее[0..*]
    }

    class "КонфигурацияПК" as pcConfig extends item {

    }

}

basket ..> item
slot "0" <-- "1" part: Установлена в  

partManager ..> slot
partManager ..> part
partManager --> pcConfig

pcBuild ..> partBuild: Создаёт

pcBuild   --> partManager
partBuild --> partManager

pcBuild --> basketManager
partManager --> basketManager

basketManager ..> basket 

@enduml