@startuml


rectangle selector [{{
    salt 
    salt
    {+
    { [<&caret-left> Назад] | <&magnifying-glass> поиск: |"Inte                                  " | ^ Производитель ^ }
    {
    {SI
    {#
            <b>Тип</b> | <b>Название</b> | <b>Производитель</b> | <b>Стоимость</b> | . | .
            Процессор | Название | NoName | 12'000 | Инфо <&eye> | Выбрать <&check>
            Процессор | Название | NoName | 12'000 | Инфо <&eye> | Выбрать <&check>
            Процессор | Название | NoName | 12'000 | Инфо <&eye> | Выбрать <&check>
            Процессор | Название | NoName | 12'000 | Инфо <&eye> | Выбрать <&check>
            Процессор | Название | NoName | 12'000 | Инфо <&eye> | Выбрать <&check>
            Процессор | Название | NoName | 12'000 | Инфо <&eye> | Выбрать <&check>
            Процессор | Название | NoName | 12'000 | Инфо <&eye> | Выбрать <&check>
            Процессор | Название | NoName | 12'000  | Инфо <&eye> | Выбрать <&check>
        }
    } | {^== Фильтры
        {T
        + Процессор
        ++ Тип сокета
        +++ [] Тип 1
        +++ [] Тип 2
        +++ [] Тип 3
        ++ Частота
        +++ []...
        +++ []...
        +++ []...
        }
    }
    }
    }
}}]

rectangle pc_editor [{{
salt
{+
    { [<&basket> корзина] | <&magnifying-glass> поиск: |"                                    " | ^ Производитель ^ IBM PC ^ AMD ^ ... ^ | ^ Тип        ^ Серверный ПК ^ Настольный ПК ^ Планшетный ПК <&check> ^ Портативный ПК <&check> ^ }
    {/ <b>Сборка ПК</b> | Комплектующие & Переферия  }
    {
        {^==Готовые комплекты  <&caret-left>            
        {SI
        Для домашних серверов   |  <&caret-right>
        Компьютер для игр       |  <&caret-right>
        Офисная машина          |  <&caret-right>
        Машина для учёбы        |  <&caret-right>
        Умный дом               |  <&caret-right>
        Для ретрогейменга       |  <&caret-right>
        Для дата сатанистов     |  <&caret-right>
        Заглушка     |  <&caret-right>
        Заглушка     |  <&caret-right>
        Заглушка     |  <&caret-right>
        Заглушка     |  <&caret-right>
        Заглушка     |  <&caret-right>
        Заглушка     |  <&caret-right>
        Заглушка     |  <&caret-right>
        Заглушка     |  <&caret-right>
        Заглушка     |  <&caret-right>
        Заглушка     |  <&caret-right>
        }
        } | {^==Свой комплект
            {^==Тип ПК
                (X) Серверный ПК
                ( ) Настольный ПК
                ( ) Планшетный ПК
                ( ) Портативный ПК
            }
            {^==Слоты
                {SI
                {#
                Процессор №1   | <ПУСТО> | Автоподбор <&star>  | Смотреть варианты <&caret-right>
                Процессор №2   | Intel Celeron | Очистить <&x> | Смотреть варианты <&caret-right>
                Слот памяти №1 | <Пусто> |  Автоподбор <&star> | Смотреть варианты <&caret-right>
                Слот памяти №2 | <Пусто> |  Автоподбор <&star> | Смотреть варианты <&caret-right>
                Слот памяти №3 | <Пусто> |  Автоподбор <&star> | Смотреть варианты <&caret-right> 
                }
                <b>ИТОГО</b>: 64'000 ₽
                }
                [Добавить в корзину]
            }

        }
    }
}
}
}}]
 
rectangle component_search [{{
    salt
    {+
    { [<&basket> корзина] | <&magnifying-glass> поиск: |"Macin                                 " | ^ Производитель ^ | ^ Тип        ^ Серверный ПК ^ Настольный ПК ^ Планшетный ПК <&check> ^ Портативный ПК <&check> ^ }
    {/ Сборка ПК | <b>Комплектующие & Переферия</b>  }
    {
    {SI
    {#
            <b>Тип</b> | <b>Название</b> | <b>Производитель</b> | <b>Стоимость</b> | . | .
            ОЗУ | Название | NoName | 12'000 | Инфо <&eye> | В корзину <&basket>
            ОЗУ | Название | NoName | 12'000 | Инфо <&eye>| В корзину <&basket>
            ОЗУ | Название | NoName | 12'000 | Инфо <&eye>| В корзину <&basket>
            Процессор | Название | NoName | 12'000 | Инфо <&eye> | В корзину <&basket>
            ОЗУ | Название | NoName | 12'000 | Инфо <&eye>| В корзину <&basket>
            ОЗУ | Название | NoName | 12'000 | Инфо <&eye>| В корзину <&basket>
            Диск | Название | NoName | 12'000 | Инфо <&eye>| В корзину <&basket>
            ОЗУ | Название | NoName | 12'000  | Инфо <&eye>| В корзину <&basket>
        }
    } | {^==Категории
            "                "
            {T
              + Устройства
              ++ Переферия
              +++ [] Звук
              ++++ [] Наушники
              ++ Мониторы
              +++ Накопители
              ++ [X] Комплектующие
              +++ [X] Накопители
              +++ [X] Процессор
              +++ [X] Память
            }
    } | {^== Фильтры
        {T
        + Внутренние накопители
        ++ Тип
        +++ [] HDD
        +++ [] SSD
        ++ Объем
        +++ [] 128ГБ - 512Гб
        +++ [] 512ГБ - 1Гб
        +++ [] ...
        + Процессор
        ++ Тип сокета
        +++ [] Тип 1
        +++ [] Тип 2
        +++ [] Тип 3
        }
    }
    }
    }
}}]

circle "Вход на сайт" as C
C --> pc_editor
pc_editor --> component_search: " Вкладка «Комплектующие & Переферия» "
pc_editor --> component_search: " «Поиск» → «⬎» "

pc_editor --> selector: " «Смотреть варианты» "
pc_editor <-- selector: " «Выбрать» "
pc_editor <-- selector: " «Назад» "

@enduml